-- =====================================================
-- NOTIFICATIONS TABLE SETUP
-- =====================================================

-- Create notifications table
CREATE TABLE IF NOT EXISTS notifications (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  message TEXT NOT NULL,
  type TEXT NOT NULL CHECK (type IN ('info', 'success', 'warning', 'error')),
  read BOOLEAN DEFAULT FALSE,
  action_url TEXT,
  action_text TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_notifications_user_id ON notifications(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_read ON notifications(user_id, read);
CREATE INDEX IF NOT EXISTS idx_notifications_created_at ON notifications(created_at DESC);

-- Create trigger for updated_at
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

DROP TRIGGER IF EXISTS set_notifications_updated_at ON notifications;
CREATE TRIGGER set_notifications_updated_at
  BEFORE UPDATE ON notifications
  FOR EACH ROW
  EXECUTE FUNCTION set_updated_at();

-- Enable RLS
ALTER TABLE notifications ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
-- Users can read their own notifications
CREATE POLICY "Users can read their own notifications" ON notifications
  FOR SELECT USING (auth.uid() = user_id);

-- Users can insert their own notifications (system use)
CREATE POLICY "Users can insert their own notifications" ON notifications
  FOR INSERT WITH CHECK (auth.uid() = user_id);

-- Users can update their own notifications (mark as read)
CREATE POLICY "Users can update their own notifications" ON notifications
  FOR UPDATE USING (auth.uid() = user_id);

-- Users can delete their own notifications
CREATE POLICY "Users can delete their own notifications" ON notifications
  FOR DELETE USING (auth.uid() = user_id);

-- =====================================================
-- REALTIME SETUP
-- =====================================================

-- Enable realtime for notifications
ALTER PUBLICATION supabase_realtime ADD TABLE notifications;

-- =====================================================
-- SAMPLE NOTIFICATIONS (for testing)
-- =====================================================

-- This will be automatically generated by the system
-- but here are some examples for manual testing:

/*
INSERT INTO notifications (user_id, title, message, type, action_url, action_text) VALUES
('USER_ID_HERE', 'Bem-vindo ao Intentia!', 'Sua conta foi configurada com sucesso. Comece criando seu primeiro projeto.', 'success', '/projects', 'Criar Projeto'),
('USER_ID_HERE', 'Análise Concluída', 'Seu primeiro projeto foi analisado. Confira os insights gerados.', 'info', '/dashboard', 'Ver Dashboard'),
('USER_ID_HERE', 'Dica Rápida', 'Sabia que você pode fazer benchmark competitivo? Compare-se com concorrentes.', 'info', '/benchmark', 'Explorar');
*/

-- =====================================================
-- CLEANUP FUNCTION (optional)
-- =====================================================

-- Function to clean old notifications (older than 30 days)
CREATE OR REPLACE FUNCTION cleanup_old_notifications()
RETURNS void AS $$
BEGIN
  DELETE FROM notifications 
  WHERE created_at < NOW() - INTERVAL '30 days'
  AND read = TRUE;
END;
$$ LANGUAGE plpgsql;

-- You can call this function periodically or set up a cron job
-- SELECT cleanup_old_notifications();
