-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.ad_integrations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['google_ads'::text, 'meta_ads'::text, 'linkedin_ads'::text, 'tiktok_ads'::text])),
  status text NOT NULL DEFAULT 'disconnected'::text CHECK (status = ANY (ARRAY['connected'::text, 'disconnected'::text, 'error'::text, 'expired'::text, 'syncing'::text])),
  access_token text,
  refresh_token text,
  token_expires_at timestamp with time zone,
  account_id text,
  account_name text,
  account_currency text DEFAULT 'BRL'::text,
  sync_enabled boolean NOT NULL DEFAULT false,
  sync_frequency text NOT NULL DEFAULT 'daily'::text CHECK (sync_frequency = ANY (ARRAY['hourly'::text, 'daily'::text, 'weekly'::text, 'manual'::text])),
  last_sync_at timestamp with time zone,
  next_sync_at timestamp with time zone,
  project_mappings jsonb DEFAULT '[]'::jsonb,
  scopes ARRAY DEFAULT '{}'::text[],
  metadata jsonb DEFAULT '{}'::jsonb,
  error_message text,
  error_count integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT ad_integrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.admin_audit_log (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  admin_id uuid NOT NULL,
  action text NOT NULL,
  target_table text,
  target_id text,
  details jsonb,
  ip_address text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_audit_log_pkey PRIMARY KEY (id),
  CONSTRAINT admin_audit_log_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin_users(id)
);
CREATE TABLE public.admin_users (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  cnpj text NOT NULL UNIQUE,
  password_hash text NOT NULL,
  name text NOT NULL DEFAULT 'Admin'::text,
  role text NOT NULL DEFAULT 'founder'::text CHECK (role = ANY (ARRAY['founder'::text, 'admin'::text, 'support'::text])),
  is_active boolean NOT NULL DEFAULT true,
  last_login_at timestamp with time zone,
  login_attempts integer NOT NULL DEFAULT 0,
  locked_until timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT admin_users_pkey PRIMARY KEY (id)
);
CREATE TABLE public.audiences (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  description text NOT NULL,
  industry text,
  company_size text CHECK (company_size = ANY (ARRAY['startup'::text, 'small'::text, 'medium'::text, 'large'::text, 'enterprise'::text])),
  location text,
  keywords ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  project_id uuid,
  deleted_at timestamp with time zone,
  icp_enrichment jsonb,
  icp_enriched_at timestamp with time zone,
  CONSTRAINT audiences_pkey PRIMARY KEY (id),
  CONSTRAINT audiences_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.audit_log (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid,
  table_name text NOT NULL,
  record_id uuid,
  operation text NOT NULL CHECK (operation = ANY (ARRAY['INSERT'::text, 'UPDATE'::text, 'DELETE'::text])),
  old_data jsonb,
  new_data jsonb,
  changed_fields ARRAY,
  ip_address text,
  user_agent text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT audit_log_pkey PRIMARY KEY (id)
);
CREATE TABLE public.benchmarks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  competitor_name text NOT NULL,
  competitor_url text NOT NULL,
  competitor_niche text NOT NULL,
  overall_score integer NOT NULL DEFAULT 0 CHECK (overall_score >= 0 AND overall_score <= 100),
  value_proposition_score integer NOT NULL DEFAULT 0 CHECK (value_proposition_score >= 0 AND value_proposition_score <= 100),
  value_proposition_analysis text,
  offer_clarity_score integer NOT NULL DEFAULT 0 CHECK (offer_clarity_score >= 0 AND offer_clarity_score <= 100),
  offer_clarity_analysis text,
  user_journey_score integer NOT NULL DEFAULT 0 CHECK (user_journey_score >= 0 AND user_journey_score <= 100),
  user_journey_analysis text,
  channel_presence jsonb DEFAULT '{}'::jsonb,
  channel_effectiveness jsonb DEFAULT '{}'::jsonb,
  strengths ARRAY DEFAULT '{}'::text[],
  weaknesses ARRAY DEFAULT '{}'::text[],
  opportunities ARRAY DEFAULT '{}'::text[],
  threats ARRAY DEFAULT '{}'::text[],
  strategic_insights text,
  recommendations text,
  analysis_date timestamp with time zone NOT NULL DEFAULT now(),
  last_update timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  ai_analysis jsonb,
  structured_data jsonb,
  html_snapshot text,
  html_snapshot_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT benchmarks_pkey PRIMARY KEY (id),
  CONSTRAINT benchmarks_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.budget_allocations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['google'::text, 'meta'::text, 'linkedin'::text, 'tiktok'::text])),
  month integer NOT NULL CHECK (month >= 1 AND month <= 12),
  year integer NOT NULL CHECK (year >= 2020 AND year <= 2100),
  planned_budget numeric DEFAULT 0,
  actual_spent numeric DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT budget_allocations_pkey PRIMARY KEY (id),
  CONSTRAINT budget_allocations_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.campaign_metrics (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  campaign_id uuid NOT NULL,
  user_id uuid NOT NULL,
  period_start date NOT NULL,
  period_end date NOT NULL,
  impressions integer DEFAULT 0,
  clicks integer DEFAULT 0,
  ctr numeric DEFAULT 0,
  cpc numeric DEFAULT 0,
  cpm numeric DEFAULT 0,
  conversions integer DEFAULT 0,
  cpa numeric DEFAULT 0,
  roas numeric DEFAULT 0,
  cost numeric DEFAULT 0,
  custom_metrics jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  reach integer DEFAULT 0,
  frequency numeric DEFAULT 0,
  video_views integer DEFAULT 0,
  vtr numeric DEFAULT 0,
  leads integer DEFAULT 0,
  cpl numeric DEFAULT 0,
  quality_score numeric DEFAULT 0,
  avg_position numeric DEFAULT 0,
  search_impression_share numeric DEFAULT 0,
  engagement_rate numeric DEFAULT 0,
  revenue numeric DEFAULT 0,
  notes text DEFAULT ''::text,
  source text DEFAULT 'manual'::text CHECK (source = ANY (ARRAY['manual'::text, 'api'::text, 'import'::text])),
  sessions integer DEFAULT 0,
  first_visits integer DEFAULT 0,
  leads_month integer DEFAULT 0,
  mql_rate numeric DEFAULT 0,
  sql_rate numeric DEFAULT 0,
  clients_web integer DEFAULT 0,
  revenue_web numeric DEFAULT 0,
  avg_ticket numeric DEFAULT 0,
  google_ads_cost numeric DEFAULT 0,
  cac_month numeric DEFAULT 0,
  cost_per_conversion numeric DEFAULT 0,
  ltv numeric DEFAULT 0,
  cac_ltv_ratio numeric DEFAULT 0,
  cac_ltv_benchmark numeric DEFAULT 3,
  roi_accumulated numeric DEFAULT 0,
  roi_period_months integer DEFAULT 0,
  CONSTRAINT campaign_metrics_pkey PRIMARY KEY (id),
  CONSTRAINT campaign_metrics_campaign_id_fkey FOREIGN KEY (campaign_id) REFERENCES public.campaigns(id)
);
CREATE TABLE public.campaigns (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  project_id uuid NOT NULL,
  tactical_plan_id uuid,
  tactical_channel_plan_id uuid,
  name text NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['google'::text, 'meta'::text, 'linkedin'::text, 'tiktok'::text])),
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'active'::text, 'paused'::text, 'completed'::text, 'archived'::text])),
  objective text,
  notes text,
  budget_total numeric DEFAULT 0,
  budget_spent numeric DEFAULT 0,
  start_date date,
  end_date date,
  is_deleted boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  performance_ai_analysis jsonb,
  performance_ai_analyzed_at timestamp with time zone,
  CONSTRAINT campaigns_pkey PRIMARY KEY (id),
  CONSTRAINT campaigns_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT campaigns_tactical_plan_id_fkey FOREIGN KEY (tactical_plan_id) REFERENCES public.tactical_plans(id),
  CONSTRAINT campaigns_tactical_channel_plan_id_fkey FOREIGN KEY (tactical_channel_plan_id) REFERENCES public.tactical_channel_plans(id)
);
CREATE TABLE public.contact_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  email text NOT NULL,
  company text,
  phone text,
  message text NOT NULL,
  status text DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'read'::text, 'replied'::text, 'archived'::text])),
  notes text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT contact_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.copy_frameworks (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tactical_plan_id uuid NOT NULL,
  user_id uuid NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['google'::text, 'meta'::text, 'linkedin'::text, 'tiktok'::text])),
  framework_type text NOT NULL CHECK (framework_type = ANY (ARRAY['pain_solution_proof_cta'::text, 'comparison'::text, 'authority'::text, 'custom'::text])),
  framework_name text NOT NULL,
  structure jsonb NOT NULL DEFAULT '{}'::jsonb,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT copy_frameworks_pkey PRIMARY KEY (id),
  CONSTRAINT copy_frameworks_tactical_plan_id_fkey FOREIGN KEY (tactical_plan_id) REFERENCES public.tactical_plans(id)
);
CREATE TABLE public.feature_flags (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  feature_key text NOT NULL UNIQUE,
  feature_name text NOT NULL,
  description text,
  category text NOT NULL DEFAULT 'general'::text CHECK (category = ANY (ARRAY['analysis'::text, 'ai'::text, 'benchmark'::text, 'tactical'::text, 'export'::text, 'social'::text, 'general'::text, 'admin'::text, 'integrations'::text, 'seo_performance'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'disabled'::text, 'development'::text, 'maintenance'::text, 'deprecated'::text])),
  status_message text,
  icon text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT feature_flags_pkey PRIMARY KEY (id)
);
CREATE TABLE public.insights (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid NOT NULL,
  user_id uuid NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['warning'::text, 'opportunity'::text, 'improvement'::text])),
  title text NOT NULL,
  description text NOT NULL,
  action text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  source text NOT NULL DEFAULT 'heuristic'::text CHECK (source = ANY (ARRAY['heuristic'::text, 'ai'::text])),
  ai_enrichment jsonb,
  priority text CHECK (priority = ANY (ARRAY['critical'::text, 'high'::text, 'medium'::text, 'low'::text])),
  ai_provider text,
  ai_model text,
  ai_enriched_at timestamp with time zone,
  CONSTRAINT insights_pkey PRIMARY KEY (id),
  CONSTRAINT insights_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.integration_sync_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  integration_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['google_ads'::text, 'meta_ads'::text, 'linkedin_ads'::text, 'tiktok_ads'::text])),
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'running'::text, 'completed'::text, 'failed'::text, 'partial'::text])),
  sync_type text NOT NULL DEFAULT 'full'::text CHECK (sync_type = ANY (ARRAY['full'::text, 'incremental'::text, 'manual'::text])),
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  duration_ms integer,
  records_fetched integer DEFAULT 0,
  records_created integer DEFAULT 0,
  records_updated integer DEFAULT 0,
  records_failed integer DEFAULT 0,
  period_start date,
  period_end date,
  error_message text,
  error_details jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT integration_sync_logs_pkey PRIMARY KEY (id),
  CONSTRAINT integration_sync_logs_integration_id_fkey FOREIGN KEY (integration_id) REFERENCES public.ad_integrations(id)
);
CREATE TABLE public.notifications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  title text NOT NULL,
  message text NOT NULL,
  type text NOT NULL CHECK (type = ANY (ARRAY['info'::text, 'success'::text, 'warning'::text, 'error'::text])),
  read boolean DEFAULT false,
  action_url text,
  action_text text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.plan_features (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  feature_key text NOT NULL,
  plan text NOT NULL CHECK (plan = ANY (ARRAY['starter'::text, 'professional'::text, 'enterprise'::text])),
  is_enabled boolean NOT NULL DEFAULT true,
  usage_limit integer,
  limit_period text CHECK (limit_period = ANY (ARRAY['daily'::text, 'weekly'::text, 'monthly'::text, 'unlimited'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT plan_features_pkey PRIMARY KEY (id),
  CONSTRAINT plan_features_feature_key_fkey FOREIGN KEY (feature_key) REFERENCES public.feature_flags(feature_key)
);
CREATE TABLE public.platform_incident_updates (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  incident_id uuid NOT NULL,
  status text NOT NULL CHECK (status = ANY (ARRAY['investigating'::text, 'identified'::text, 'monitoring'::text, 'resolved'::text])),
  message text NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_incident_updates_pkey PRIMARY KEY (id),
  CONSTRAINT platform_incident_updates_incident_id_fkey FOREIGN KEY (incident_id) REFERENCES public.platform_incidents(id)
);
CREATE TABLE public.platform_incidents (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  status text NOT NULL DEFAULT 'investigating'::text CHECK (status = ANY (ARRAY['investigating'::text, 'identified'::text, 'monitoring'::text, 'resolved'::text])),
  severity text NOT NULL DEFAULT 'minor'::text CHECK (severity = ANY (ARRAY['minor'::text, 'major'::text, 'critical'::text])),
  affected_services ARRAY DEFAULT '{}'::uuid[],
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  resolved_at timestamp with time zone,
  CONSTRAINT platform_incidents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_maintenances (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  description text,
  status text NOT NULL DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'in_progress'::text, 'completed'::text, 'cancelled'::text])),
  affected_services ARRAY DEFAULT '{}'::uuid[],
  scheduled_start timestamp with time zone NOT NULL,
  scheduled_end timestamp with time zone NOT NULL,
  actual_start timestamp with time zone,
  actual_end timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_maintenances_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_services (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  description text,
  category text NOT NULL DEFAULT 'Core'::text,
  icon text DEFAULT 'Server'::text,
  status text NOT NULL DEFAULT 'operational'::text CHECK (status = ANY (ARRAY['operational'::text, 'degraded'::text, 'partial_outage'::text, 'major_outage'::text, 'maintenance'::text])),
  sort_order integer DEFAULT 0,
  is_visible boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_services_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_status_subscribers (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  email text NOT NULL UNIQUE,
  is_verified boolean DEFAULT false,
  verification_token text,
  unsubscribe_token text NOT NULL DEFAULT encode(gen_random_bytes(32), 'hex'::text),
  subscribed_at timestamp with time zone DEFAULT now(),
  verified_at timestamp with time zone,
  unsubscribed_at timestamp with time zone,
  is_active boolean DEFAULT true,
  CONSTRAINT platform_status_subscribers_pkey PRIMARY KEY (id)
);
CREATE TABLE public.platform_uptime_daily (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  service_id uuid,
  date date NOT NULL,
  status text NOT NULL DEFAULT 'operational'::text CHECK (status = ANY (ARRAY['operational'::text, 'degraded'::text, 'partial_outage'::text, 'major_outage'::text, 'maintenance'::text])),
  uptime_percentage numeric NOT NULL DEFAULT 100.000,
  response_time_ms integer,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT platform_uptime_daily_pkey PRIMARY KEY (id),
  CONSTRAINT platform_uptime_daily_service_id_fkey FOREIGN KEY (service_id) REFERENCES public.platform_services(id)
);
CREATE TABLE public.project_channel_scores (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid NOT NULL,
  user_id uuid NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['google'::text, 'meta'::text, 'linkedin'::text, 'tiktok'::text])),
  score integer NOT NULL DEFAULT 0,
  objective text,
  funnel_role text,
  is_recommended boolean NOT NULL DEFAULT true,
  risks ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT project_channel_scores_pkey PRIMARY KEY (id),
  CONSTRAINT project_channel_scores_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  name text NOT NULL,
  niche text NOT NULL,
  url text NOT NULL,
  score integer NOT NULL DEFAULT 0,
  status text NOT NULL CHECK (status = ANY (ARRAY['pending'::text, 'analyzing'::text, 'completed'::text])),
  last_update timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  competitor_urls ARRAY DEFAULT '{}'::text[],
  heuristic_analysis jsonb,
  heuristic_completed_at timestamp with time zone,
  ai_analysis jsonb,
  ai_completed_at timestamp with time zone,
  html_snapshot text,
  structured_data jsonb,
  html_snapshot_at timestamp with time zone,
  deleted_at timestamp with time zone,
  CONSTRAINT projects_pkey PRIMARY KEY (id)
);
CREATE TABLE public.rate_limits (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  action_type text NOT NULL,
  window_start timestamp with time zone NOT NULL DEFAULT now(),
  request_count integer NOT NULL DEFAULT 1,
  CONSTRAINT rate_limits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.segmentation_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tactical_plan_id uuid NOT NULL,
  user_id uuid NOT NULL,
  audience_id uuid,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['google'::text, 'meta'::text, 'linkedin'::text, 'tiktok'::text])),
  audience_name text NOT NULL,
  targeting_criteria jsonb DEFAULT '{}'::jsonb,
  message_angle text,
  priority text CHECK (priority = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT segmentation_plans_pkey PRIMARY KEY (id),
  CONSTRAINT segmentation_plans_tactical_plan_id_fkey FOREIGN KEY (tactical_plan_id) REFERENCES public.tactical_plans(id),
  CONSTRAINT segmentation_plans_audience_id_fkey FOREIGN KEY (audience_id) REFERENCES public.audiences(id)
);
CREATE TABLE public.support_categories (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name character varying NOT NULL UNIQUE,
  slug character varying NOT NULL UNIQUE,
  description text,
  color character varying DEFAULT '#6366f1'::character varying,
  icon character varying DEFAULT 'MessageCircle'::character varying,
  sla_first_response integer DEFAULT 2,
  sla_resolution integer DEFAULT 24,
  is_active boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.support_ticket_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid,
  sender_id uuid,
  sender_type character varying NOT NULL CHECK (sender_type::text = ANY (ARRAY['client'::character varying, 'admin'::character varying]::text[])),
  message text NOT NULL,
  attachments jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  is_internal boolean DEFAULT false,
  read_at timestamp with time zone,
  CONSTRAINT support_ticket_messages_pkey PRIMARY KEY (id),
  CONSTRAINT support_ticket_messages_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id)
);
CREATE TABLE public.support_ticket_notes (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid,
  admin_id uuid,
  note text NOT NULL,
  is_visible_to_client boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_ticket_notes_pkey PRIMARY KEY (id),
  CONSTRAINT support_ticket_notes_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id)
);
CREATE TABLE public.support_ticket_ratings (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  ticket_id uuid,
  user_id uuid,
  rating integer NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT support_ticket_ratings_pkey PRIMARY KEY (id),
  CONSTRAINT support_ticket_ratings_ticket_id_fkey FOREIGN KEY (ticket_id) REFERENCES public.support_tickets(id)
);
CREATE TABLE public.support_tickets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  tenant_id uuid,
  user_id uuid,
  subject character varying NOT NULL,
  category character varying NOT NULL CHECK (category::text = ANY (ARRAY['comercial'::character varying, 'desenvolvimento'::character varying, 'financeiro'::character varying, 'duvidas'::character varying, 'sugestoes'::character varying, 'bug'::character varying, 'outros'::character varying]::text[])),
  priority character varying NOT NULL DEFAULT 'normal'::character varying CHECK (priority::text = ANY (ARRAY['baixa'::character varying, 'normal'::character varying, 'alta'::character varying, 'urgente'::character varying]::text[])),
  status character varying NOT NULL DEFAULT 'aberto'::character varying CHECK (status::text = ANY (ARRAY['aberto'::character varying, 'em_analise'::character varying, 'em_andamento'::character varying, 'aguardando_cliente'::character varying, 'resolvido'::character varying, 'cancelado'::character varying]::text[])),
  description text NOT NULL,
  attachments jsonb DEFAULT '[]'::jsonb,
  ticket_number character varying NOT NULL UNIQUE CHECK (ticket_number::text ~* '^SUP-\d{4}-\d{5}$'::text),
  assigned_to uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  first_response_at timestamp with time zone,
  resolved_at timestamp with time zone,
  sla_deadline timestamp with time zone,
  response_time_minutes integer,
  resolution_time_hours integer,
  satisfaction_score integer CHECK (satisfaction_score >= 1 AND satisfaction_score <= 5),
  CONSTRAINT support_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT support_tickets_tenant_id_fkey FOREIGN KEY (tenant_id) REFERENCES public.tenant_settings(id)
);
CREATE TABLE public.tactical_channel_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tactical_plan_id uuid NOT NULL,
  user_id uuid NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['google'::text, 'meta'::text, 'linkedin'::text, 'tiktok'::text])),
  campaign_type text,
  campaign_structure jsonb DEFAULT '{}'::jsonb,
  funnel_role text,
  funnel_stage text CHECK (funnel_stage = ANY (ARRAY['awareness'::text, 'consideration'::text, 'conversion'::text, 'retention'::text])),
  ad_group_structure jsonb DEFAULT '[]'::jsonb,
  bidding_strategy text,
  extensions_plan jsonb DEFAULT '[]'::jsonb,
  quality_score_factors jsonb DEFAULT '{}'::jsonb,
  segmentation jsonb DEFAULT '{}'::jsonb,
  key_metrics jsonb DEFAULT '[]'::jsonb,
  testing_plan jsonb DEFAULT '[]'::jsonb,
  tactical_score integer DEFAULT 0,
  coherence_score integer DEFAULT 0,
  clarity_score integer DEFAULT 0,
  segmentation_score integer DEFAULT 0,
  alerts jsonb DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT tactical_channel_plans_pkey PRIMARY KEY (id),
  CONSTRAINT tactical_channel_plans_tactical_plan_id_fkey FOREIGN KEY (tactical_plan_id) REFERENCES public.tactical_plans(id)
);
CREATE TABLE public.tactical_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  project_id uuid NOT NULL UNIQUE,
  user_id uuid NOT NULL,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'in_progress'::text, 'completed'::text])),
  overall_tactical_score integer DEFAULT 0,
  strategic_coherence_score integer DEFAULT 0,
  structure_clarity_score integer DEFAULT 0,
  segmentation_quality_score integer DEFAULT 0,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  deleted_at timestamp with time zone,
  CONSTRAINT tactical_plans_pkey PRIMARY KEY (id),
  CONSTRAINT tactical_plans_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id)
);
CREATE TABLE public.tenant_settings (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL UNIQUE,
  company_name text NOT NULL,
  plan text NOT NULL CHECK (plan = ANY (ARRAY['starter'::text, 'professional'::text, 'enterprise'::text])),
  monthly_analyses_limit integer NOT NULL DEFAULT 1,
  analyses_used integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  full_name text,
  email text,
  max_audiences integer NOT NULL DEFAULT 5,
  CONSTRAINT tenant_settings_pkey PRIMARY KEY (id)
);
CREATE TABLE public.testing_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  tactical_plan_id uuid NOT NULL,
  user_id uuid NOT NULL,
  channel text NOT NULL CHECK (channel = ANY (ARRAY['google'::text, 'meta'::text, 'linkedin'::text, 'tiktok'::text])),
  test_name text NOT NULL,
  hypothesis text NOT NULL,
  what_to_test text NOT NULL,
  success_criteria text NOT NULL,
  priority text CHECK (priority = ANY (ARRAY['high'::text, 'medium'::text, 'low'::text])),
  status text NOT NULL DEFAULT 'planned'::text CHECK (status = ANY (ARRAY['planned'::text, 'running'::text, 'completed'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT testing_plans_pkey PRIMARY KEY (id),
  CONSTRAINT testing_plans_tactical_plan_id_fkey FOREIGN KEY (tactical_plan_id) REFERENCES public.tactical_plans(id)
);
CREATE TABLE public.user_api_keys (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  provider text NOT NULL CHECK (provider = ANY (ARRAY['google_gemini'::text, 'anthropic_claude'::text])),
  api_key_encrypted text NOT NULL,
  preferred_model text,
  is_active boolean NOT NULL DEFAULT true,
  last_validated_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_api_keys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_data_backups (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  backup_type text NOT NULL CHECK (backup_type = ANY (ARRAY['auto'::text, 'manual'::text, 'pre_delete'::text])),
  backup_data jsonb NOT NULL,
  tables_included ARRAY NOT NULL,
  record_counts jsonb NOT NULL,
  size_bytes bigint,
  checksum text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  expires_at timestamp with time zone NOT NULL DEFAULT (now() + '90 days'::interval),
  CONSTRAINT user_data_backups_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_feature_overrides (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  feature_key text NOT NULL,
  is_enabled boolean NOT NULL,
  reason text,
  admin_id uuid,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT user_feature_overrides_pkey PRIMARY KEY (id),
  CONSTRAINT user_feature_overrides_feature_key_fkey FOREIGN KEY (feature_key) REFERENCES public.feature_flags(feature_key),
  CONSTRAINT user_feature_overrides_admin_id_fkey FOREIGN KEY (admin_id) REFERENCES public.admin_users(id)
);